### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#129]
I've just built Shuttl from tag v0.8.3.1 and deployed to my Splunk 5.0.2 server. I'm getting 404 errors on the 'Flush' and 'Thaw' screens.

The path '/splunk/en-GB/custom/shuttl/Archiving/show' was not found.
The path '/splunk/en-GB/custom/shuttl/Archiving/show_flush' was not found.

Also I'm archiving to S3 and that seems to be working as I can see the buckets appearing in the AWS S3 console, however the buckets are all marked as failed in Shuttl.

**Comment by petterik** [comment]
I'm not getting the error with the build from tag v0.8.3.1.

Did you restart Splunk after installing Shuttl? Even though Splunk doesn't say it needs a restart, it needs one, since the UI is build with custom python scripts and xml.
Also, make sure that shuttl/conf/splunk.xml is correct.

If it's still not working, try to see if you can find anything in either $SPLUNK_HOME/var/log/splunk/shuttl.log or inspect what happens in your browser with chrome or firebug.
I wasn't involved with the UI dev, so I'll ask someone how to debug the UI if you're still having this problem.

I'm currently thinking a lot about the S3 implementation and the bucket's shouldn't be marked as failed in an upcoming release. Thanks for reporting that bug.

**Comment by msnelling** [comment]
This was after a fresh install of Shuttl, Splunk had been restarted but the indexes weren't yet configured for archiving.
Now that archiving has been set up and some buckets have been frozen to S3 the problem has gone away.
