### ISSUE TITLE
Enable Server-Side Encyption with S3

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#130]
This is desirable for financial services compliance reasons. See the link below for enabling SSE in the Java API.
http://docs.aws.amazon.com/AmazonS3/latest/dev/SSEUsingJavaSDK.html

**Comment by petterik** [comment]
Shuttl is currently using Hadoop's S3 file system implementation, which doesn't support this. An S3 implementation of Shuttl's ArchiveFileSystem interface would have to be done, using AWS own SDK to support this.

I might do this, since it seems like most users of Shuttl use S3 and I'm not in control of what can be improved as long as I'm using Hadoop's implementation.

Keeping the issue open
