### ISSUE TITLE
add amazon glacier backend

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#74]
http://aws.amazon.com/glacier/

**Comment by borischen** [comment]
http://docs.amazonwebservices.com/amazonglacier/2012-06-01/dev/using-aws-sdk-for-java.html

**Comment by petterik** [comment]
"I have a question, if I have many files in glacier, more than 1000000 files, and I want to retrieve them.

How many jobs can I create at one time ?
Can I create 1000000 jobs at one time, only wait 3-5 hours, and start to retrieve them after 3-5 hours ?"

From: https://forums.aws.amazon.com/thread.jspa?threadID=104867&tstart=0

**Comment by petterik** [comment]
"Every job should complete after ~4 hours"

From: https://forums.aws.amazon.com/thread.jspa?threadID=102750&tstart=100

Maybe glacier is only suitable for "stripped buckets", with raw only, and re-building the buckets when they are in thaw. Need to experiment.

**Comment by petterik** [comment]
Configuration suggestion:
glacier://<ID>:<SECRET>@endpoint/<vault>

**Comment by petterik** [comment]
Good example of how to parse the vault inventory request:
https://github.com/MoriTanosuke/glacieruploader/blob/master/src/main/java/de/kopis/glacier/util/VaultInventoryPrinter.java

**Comment by petterik** [comment]
Configuration uri change:
glacier://<ID>:<SECRET>@<endpoint>:<s3bucket>/<vault>
, where vault also serves as the archiving root on s3.
The reason for the change is because glacier is using part glacier and part s3 (which is hardcoded to s3n atm).
I'm not sure this is the way of going forward, instead we could have separate uris, configs and/or property files. Or we could keep it this way.

**Comment by borischen** [comment]
prefer breaking out values into a config file. Worried about cramming too much into a "url"

**Comment by petterik** [comment]
What's left to do:
- Breaking out vaules into different config files, which probably means redesigning the configuration a little.
- Persisting/Caching ArchiveIDs. When downloading a file from glacier a special ArchiveId is needed. I've mapped it to a unique URI (the archiving path), but it's only stored in memory atm. A reboot of the system would not have any ArchiveIDs. It's possible but expensive to get them from glacier. It takes around 4 hour and some $$.
- Integration testing it with glacier! To see if it actually works :)

I suggest that we close this issue and split those into new issues that are prioritized. 
The Persisting/Caching of ArchiveIDs could be done by a master/spacecraft, which might be created when making Splunk 5.0 support. More on this later.

**Comment by petterik** [comment]
Re-made the configuration so that it's done with property files instead of with a URI. This issue is getting too big. Created issues for everything that's left to do:
- New configuration needs to be documented, #93
- Integration testing with glacer, #94 (Should take around 4hours to test).

Closing the issue.
