### ISSUE TITLE
archiveBucket.sh has problem with 'exec -a'

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#77]
On my Ubuntu 12.04 x64 server installation it looks like that this script isn't interpreting 'exec -a' correctly.

I was able to hack this by setting changing the to #!/bin/bash instead. This obviously isn't a great solution though.

**Comment by petterik** [comment]
I will just remove the -a option to exec, since it's not needed. It was previously used for debugging purposes. 
Expect to see it on the develop branch later today, or in the release by the end of the month.

@msnelling you might also suffer from Shuttl servers staying alive Splunk has stopped or restarted. This depends on if Ubuntu 12.04 uses dash as shell or not. See issue #76 for more info.
