### ISSUE TITLE
Thaw and Flush menus not working

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#83]
Both menus return a 404 and the following message

`The path '/en-GB/custom/shuttl/Archiving/show_flush' was not found.`

**Comment by petterik** [comment]
I could reproduce the behavior by installing Shuttl on an existing running Splunk, and without restarting Splunk, going to Shuttl's Thaw and Flush menus.
The issue was resolved when I restarted Splunk.

Have you restarted the Splunk that Shuttl is installed on, or no?

However, there should be a way to install the app without restarting Splunk. I'm on it!

**Comment by petterik** [comment]
There is no way at this time to reload custom controllers, which is they way we've written the current UI.

Splunk needs to be restarted to use the UI.
We might redo the UI later in a way that does not have this flaw.

I'm sorry for the inconvenience.

Please get back to me if you're still getting this error after having restarted Splunk.

**Comment by msnelling** [comment]
Yes a restart fixed the issue thanks.
